# Deploy Version
version: '3.7'
services:
  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"
      env_file:
        # Server
        - './backend/monitoring/grafana/env.grafana'
        
      volumes:
        # Server
        - './backend/monitoring/grafana:/var/lib/grafana'
      depends_on:
        - prometheus
      user: root  
      restart: always
      networks:
        - monitoring
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      # Server
      - ./backend/monitoring/prometheus/config:/etc/prometheus
      - ./backend/monitoring/prometheus/volume:/prometheus
    ports:
      - 9090:9090
    command: # web.enalbe-lifecycle은 api 재시작없이 설정파일들을 reload 할 수 있게 해줌
      - '--web.enable-lifecycle'
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    user: root
    restart: always
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge