version: '3'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - '/backend/data/grafana/env.grafana'
    volumes:
      - '/data/grafana:/var/lib/grafana'
    restart: always
    networks:
      - promnet
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - '/backend/data/mysql/env.mysql'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - '/data/mysql/data:/var/lib/mysql'
      - '/data/mysql/etc:/etc/mysql/conf.d'
    restart: always
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./backend/data/prometheus/config:/etc/prometheus
      - ./backend/data/prometheus/volume:/prometheus
    ports:
      - 9090:9090
    command: # web.enalbe-lifecycle은 api 재시작없이 설정파일들을 reload 할 수 있게 해줌
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - promnet
  api:
    build:
      context: /backend/data/python
      dockerfile: Dockerfile
    container_name: api
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:5000
    ports:
      - "5000:5000"
    volumes:
      - /data/python:/app
    restart: always

networks:
  promnet:
    driver: bridge